# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6a16db6db06f28dfb70424fbebab39178be6e8cf55004d11f1ef0f1ebe04763e4026be0e1adbe571af0d5391145974902c81cc76c4e32484bef92b50e2af636

test:
  secret_key_base: 959d286ce25d91ed503014a7f05177c7513cd947419cd56c081ae92f55f62c5e003e96d4ae2c1a5974de730ca17cb2cac73df69eec512f5211de4a1c85d9bbca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
